name: actito_assets
description: "Actito Assets Flutter Plugin: Add powerful contextual marketing features to your apps. Show the right content to the right users at the right time or location."
version: 5.1.0
homepage: https://actito.com
documentation: https://developers.actito.com/docs/push-implementation/flutter/implementation/
repository: https://github.com/actito/actito-sdk-flutter/tree/main/actito_assets

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  actito: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.0

dependency_overrides:
  actito:
    path: ../actito
  actito_flutter:
    path: ../actito_flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.actito.assets.flutter
        pluginClass: ActitoAssetsPlugin
      ios:
        pluginClass: ActitoAssetsPlugin
