desc <<-DESC
Updates the versions of the native libraries.

#### Options
* `version`: The version of the native libraries.
* `platform`: The platform to update. Leave blank to update both.

#### Examples
```sh
bundle exec fastlane update_native_libraries version:3.4.0
bundle exec fastlane update_native_libraries version:3.4.0 platform:android
bundle exec fastlane update_native_libraries version:3.4.0 platform:ios
```
DESC
lane :update_native_libraries do |options|
  version = options[:version]
  platform = options[:platform]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  if platform.nil? || platform.downcase == 'android'
    UI.message('Updating native Android libraries.')
    update_native_android_libraries(version)
  end

  if platform.nil? || platform.downcase == 'ios'
    UI.message('Updating native iOS libraries.')
    update_native_ios_libraries(version)
  end
end

desc <<-DESC
Updates the version of each Flutter package.

#### Options
* `version`: The new version for the libraries.

#### Examples
```sh
bundle exec fastlane bump version:3.4.0
```
DESC
lane :bump do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  files = Dir['../actito*/pubspec.yaml']
  regex = /^version: .*$/
  replacement = "version: #{version}"

  files.each { |file| update_file(file, regex, replacement) }

  # Update the actito_flutter dependency to ensure it matches the version of actito, as this dependency is not managed by the end user.
  actito_pubspec = "../actito/pubspec.yaml"

  dep_regex = /^\s*actito_flutter:\s*\d+\.\d+\.\d+.*$/
  dep_replacement = "  actito_flutter: #{version}"

  updated = update_file(actito_pubspec, dep_regex, dep_replacement)
end

desc <<-DESC
Updates the Android compile SDK version of each Flutter package.

#### Options
* `version`: The new version for the Android compile SDK.

#### Examples
```sh
bundle exec fastlane update_compile_sdk_version version:33
```
DESC
lane :update_compile_sdk_version do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  files = Dir['../actito*/android/build.gradle']
  regex = /compileSdkVersion .*$/
  replacement = "compileSdkVersion #{version}"

  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates Kotlin version version of each Flutter package.

#### Options
* `version`: The new version for Kotlin.

#### Examples
```sh
bundle exec fastlane update_kotlin_version version:1.7.20
```
DESC
lane :update_kotlin_version do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  files = Dir['../actito*/android/build.gradle']
  regex = /ext.kotlin_version = '.*'/
  replacement = "ext.kotlin_version = '#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates the Android Gradle Plugin version of each Flutter package.

#### Options
* `version`: The new version for the Android Gradle Plugin.

#### Examples
```sh
bundle exec fastlane update_android_gradle_plugin version:7.4.2
```
DESC
lane :update_android_gradle_plugin do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  files = Dir['../actito*/android/build.gradle']
  regex = /classpath 'com.android.tools.build:gradle:.*'/
  replacement = "classpath 'com.android.tools.build:gradle:#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates the lockfile of each package and sample app pods.

#### Examples
```sh
bundle exec fastlane update_sample
```
DESC
lane :update_sample do
  UI.message('Updating Flutter packages.')
  fetch_packages

  UI.message('Updating Cocoapods repo.')
  update_pod_repo

  UI.message('Updating app pods.')
  update_pods
end

desc <<-DESC
Validates and publishes each Flutter package.

#### Options
* `dry_run`: Only run in validation mode.

#### Examples
```sh
bundle exec fastlane publish
bundle exec fastlane publish dry_run:true
```
DESC
lane :publish do |options|
  dry_run = options[:dry_run] ||= false
  publish_arguments = dry_run ? '--dry-run' : ''

  ensure_git_status_clean unless dry_run

  # Prioritising the actito_flutter package since it is used by the core
  # actito package.
  #
  # order = actito_flutter > actito > remaining packages
  directories = Dir["../actito*"]
  directories.delete('../actito_flutter')
  directories.unshift('../actito_flutter')

  directories.each do |directory|
    if dry_run
      UI.message("Validating '#{directory}' package.")
    else
      UI.message("Publishing '#{directory}' package.")
    end

    stream_shell_command("cd #{directory} && flutter pub publish #{publish_arguments}")
  end
end


def update_file(path, regex, replacement)
  file = File.read(path)
  new_content = file.gsub(regex, replacement)
  File.open(path, 'w') { |line| line.puts new_content }
end

def update_native_android_libraries(version)
  files = Dir['../actito*/android/build.gradle']
  regex = /def actito_version = '.*'/
  replacement = "def actito_version = '#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

def update_native_ios_libraries(version)
  UI.message('Updating native iOS podspec files.')
  update_native_ios_podspec_files(version)

  UI.message('Updating native iOS SPM files.')
  update_native_ios_spm_files(version)
end

def update_native_ios_podspec_files(version)
  files = Dir['../actito*/ios/*.podspec']
  regex = /actito_version = '.*'/
  replacement = "actito_version = '#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

def update_native_ios_spm_files(version)
  files = Dir['../actito*/ios/actito*/Package.swift']
  regex = /
    (\.package\(
      \s*url:\s*"https:\/\/github\.com\/Actito\/actito-sdk-ios\.git",
      \s*from:\s*")([^"]+)
      ("\s*\),?)
  /x

  replacement = "\\1#{version}\\3"
  files.each { |file| update_file(file, regex, replacement) }
end

def fetch_packages
  directories = Dir['../actito*', '../sample']

  directories.each do |directory|
    stream_shell_command("cd #{directory} && flutter pub get")
  end
end

def update_pod_repo
  stream_shell_command("cd ../sample/ios && pod repo update")
end

def update_pods
  stream_shell_command("cd ../sample/ios && pod update")
end

def stream_shell_command(command)
  success = IO.popen(command) do |io|
    while line = io.gets
      puts line.chomp
    end

    io.close

    $?.success?
  end

  UI.user_error!("Failed to execute shell script '#{command}'") unless success
end
