name: actito_flutter
description: Internal Actito plugin. Use the `actito` plugin instead.
version: 5.0.0
homepage: https://actito.com
documentation: https://developers.actito.com/docs/push-implementation/flutter/implementation/
repository: https://github.com/actito/actito-sdk-flutter/tree/main/actito

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.actito.flutter
        pluginClass: ActitoPlugin
      ios:
        pluginClass: ActitoPlugin
